import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

import Image from 'next/image'
import * as React from 'react';
import Button from '@mui/material/Button';

import headimg from '../img/Ripfast-Logo-GOLD.jpg'
import bodyimg from '../img/Group_Ripfast_Testensity_22.jpg'
import arrowimg from '../img/arrow_3_navy.gif'
import bookimg1 from '../img/ripfast_prohormone_group-1.png'
import bookimg2 from '../img/ripfast_sarms_group.png'

import FacebookIcon from '@mui/icons-material/Facebook';
import TwitterIcon from '@mui/icons-material/Twitter';
import GoogleIcon from '@mui/icons-material/Google';
import PinterestIcon from '@mui/icons-material/Pinterest';


export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [tab, setTab] = React.useState(0);

  return (
    <>
      <Head>
        <title>Ripfast</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <header>
          <Button variant="contained" className="fixed text-black text-lg font-bold drop-shadow-2xl float-left ml-10 h-12 border border-gray-600 bg-white">Select Language</Button>
          <div className="w-full grid place-items-center">
            <Image src={headimg} alt="Head image" height={162}/>
          </div>
        </header>
        <div className="border-2 bg-white">
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">Home</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">HardCore</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">Training</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">Fat Loss</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">Accessories</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">Help</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">FAQ</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">About US</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">Blog</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">Book a Chat</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">Cart</Button>
          <Button variant="contained" className="text-lg w-40 h-16 text-black font-bold">Account</Button>
        </div>
        <div className="h-[440px]">
          <Image src={bodyimg} alt="Body image" className="object-cover	w-full h-full"/>
        </div>
        <div className="max-w-[1170px] w-full h-full text-center m-auto">
          <a style={{color:'#0f1d3b', font: '42px/56px Antoniobold'}} className="text-lg justify-center" href="https://www.ripfast.com/tdx4">
            Knowing that we've just released the STRONGEST RANGE in our company's history. You'd be crazy not to try RISK-FREE the NEW Ripfast Bodybuilding Club
            <Image className="w-[50px] mr-[30px] mt-[20px] float-right" src={arrowimg} alt="Arrow image"/>
          </a>
          <div className="grid grid-cols-2 gap-16 m-10">
            <Image src={bookimg1} width={600} alt="Book image1"/>
            <Image src={bookimg2} width={600} alt="Book image2"/>
          </div>
          <div className="w-[75%] m-10">
            <p className="text-[19px] font-sans leading-7" style={{fontFamily: 'Arial, Helvetica'}}>Ripfast produce the strongest bodybuilding supplements in Europe. 
            Our cutting edge range includes powerful designer anabolics to increase testosterone (the only true steroid alternatives on the market today). 
            As well as powerful protein, fat loss and creatine/N02 based products. All our products are backed by our 100% no quibble money back guarantee.</p>
            <a className="block w-auto p-[10px] text-white text-center bg-[#af8e5a] bg-no-repeat text-[18px] leading-[52px] rounded-2xl mt-5"
            style={{fontFamily: 'arial'}} 
            href="https://www.ripfast.com/tdx4#rbc-info">
              NEW! Get Test De Luxe Stack for just £59.99 CLICK HERE for more information
              <Image className="float-right w-[100px]" src={arrowimg} alt="Arrow image" />
            </a>
          </div>
        </div>
        <footer>
          <div className="bg-[#272727] grid grid-cols-6 gap-4 pt-[30px] pb-[30px] pl-[10px] pr-[10px]">
            <div className="pl-[15px] pr-[15px]">
              <ul className="text-[#af8e5a] text-[14px] mb-[10px] pl-[40px] leading-6">
                <li className="text-[21px] font-bold mb-[5px]">HELP CENTRE</li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">CONTACT US</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">FREQUENTLY ASKED QUESTIONS</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">QUESTIONS</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">HOW DO I PLACE AN ORDER</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">USAGE TERMS AND CONDITIONS</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">SECURITY AND PRIVACY POLICY</a></li>
              </ul>
            </div>
            <div className="pl-[15px] pr-[15px]">
              <ul className="text-[#af8e5a] text-[14px] mb-[10px] pl-[40px] leading-6">
                <li className="text-[21px] font-bold mb-[5px]">HARDCORE</li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">TEST DE LUXE STACK 4</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">SARM DE LUXE STACK</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">RIPFAST BODYBUILDING CLUB</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">TESTO INTELLIGENCE STACK</a></li>
              </ul>
            </div>
            <div className="pl-[15px] pr-[15px]">
              <ul className="text-[#af8e5a] text-[14px] mb-[10px] pl-[40px] leading-6">
                <li className="text-[21px] font-bold mb-[5px]">FAT LOSS</li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">FAT SHREDDER DE LUXE</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">CLEANSE DE LUXE</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">LEAN DE LUXE STACK</a></li>
              </ul>
            </div>
            <div className="pl-[15px] pr-[15px]">
              <ul className="text-[#af8e5a] text-[14px] mb-[10px] pl-[40px] leading-6">
                <li className="text-[21px] font-bold mb-[5px]">TRAINING</li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">PRO GYM PROTEIN</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">SUPER FULL NITRO N02</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">KRE ALKALYN CREATINE</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">RIPFAST 5000 SYSTEM</a></li>
              </ul>
            </div>
            <div className="pl-[15px] pr-[15px]">
              <ul className="text-[#af8e5a] text-[14px] mb-[10px] pl-[40px] leading-6">
                <li className="text-[21px] font-bold mb-[5px]">ACCESSORIES</li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">DESIGNER SHAKER</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">DESIGNER GLOVES</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact">NECK CHAIN</a></li>
              </ul>
            </div>
            <div className="pl-[15px] pr-[15px]">
              <ul className="text-[#af8e5a] text-[17px] mb-[10px] pl-[40px] leading-6">
                <li className="hover:underline"><a href="https://www.ripfast.com/contact"><FacebookIcon sx={{ color: '#af8e5a' }}/> Facebook</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact"><TwitterIcon sx={{ color: '#af8e5a' }}/> Twitter</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact"><GoogleIcon sx={{ color: '#af8e5a' }}/> Google +</a></li>
                <li className="hover:underline"><a href="https://www.ripfast.com/contact"><PinterestIcon sx={{ color: '#af8e5a' }}/> Pinterest</a></li>
              </ul>
            </div>
          </div>
          <div className="bg-[#222222] p-[10px] text-[11px] text-white text-center">
          © Copyright Ripfast Bodybuilding. All rights reserved
          </div>
        </footer>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
